# Generated by Django 2.2.1 on 2019-09-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fixserver',
            field=models.TextField(blank=True, null=True),
        ),
    ]
